COPY ~divine_remix/2da/A#Cyric.2DA~ ~override~

//Dread Blast innate
COPY ~Divine_Remix/spl/a#cyr07.spl~ ~override~ //Dread Blast
  SAY NAME1 @13000
  SAY UNIDENTIFIED_DESC @13010
//Create DireGuard spell
COPY ~Divine_Remix/spl/tr#cyrdg.spl~ ~override~ //Create Direguard
  SAY NAME1 @13028
  SAY UNIDENTIFIED_DESC @13029
COPY ~Divine_Remix/eff/tr#cyrdg.eff~ ~override~ 
COPY ~Divine_Remix/cre/tr#cyrdg.cre~ ~override~ //Direguard
  SAY 0x8 @13030
  SAY 0xc @13030
COPY ~Divine_Remix/spl/tr#phdg.spl~ ~override~ // innate blink
COPY ~Divine_Remix/bam/tr#cyrda.bam~ ~override~
	 ~Divine_Remix/bam/tr#cyrdb.bam~ ~override~
	 ~Divine_Remix/bam/tr#cyrdc.bam~ ~override~

COPY ~divine_remix/spl/givespell.spl~ ~override/tr#cyr7.spl~  // Give Create Direguard, lv7 Spell
  LPF ALTER_EFFECT STR_VAR resource = "tr#cyrdg" END


// change spells to innates as needed
COPY_EXISTING ~sppr601.spl~ ~override/a#cyr09.spl~ // Aerial Servant
              ~spwi509.spl~ ~override/a#cyr11.spl~ // Feeblemind
			  ~spwi811.spl~ ~override/a#cyr14.spl~ // Symbol, Fear
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

COPY ~Divine_Remix/spl/a#cyr0b.spl~ ~override~  // Razor's Edge (innate)
  SAY NAME1 @13007
  SAY UNIDENTIFIED_DESC @13008

COPY ~Divine_Remix/spl/CDXVFEAR.spl~ ~override~  // immunity to fear (permanent innate spell)

COPY ~Divine_Remix/itm/a#cyr00.itm~ ~override~  // Razor's Edge +0
  SAY NAME1 @13007
  SAY NAME2 @13007
  SAY UNIDENTIFIED_DESC @13008
  SAY DESC @13008

  SET "weap_idx" = 0

COPY_EXISTING ~a#cyr00.itm~ ~override/a#cyr01.itm~  // Razor's Edge +1
              ~a#cyr00.itm~ ~override/a#cyr02.itm~  // Razor's Edge +2
              ~a#cyr00.itm~ ~override/a#cyr03.itm~  // Razor's Edge +3
              ~a#cyr00.itm~ ~override/a#cyr04.itm~  // Razor's Edge +4
              ~a#cyr00.itm~ ~override/a#cyr05.itm~  // Razor's Edge +5
  SET "weap_idx" = ("%weap_idx%" + 1)
  WRITE_LONG  0x60 "%weap_idx%"
  WRITE_SHORT 0x86 "%weap_idx%"
  WRITE_SHORT 0x8C ("%weap_idx%" + 1)
  WRITE_SHORT 0x84 (7 - "%weap_idx%")