COPY ~divine_remix/2da/a#red.2da~ ~override~

COPY ~Divine_Remix/spl/a#re0b.spl~ ~override~  // Additional Attack per round (innate)

COPY_EXISTING ~spwi111.spl~ ~override/a#re0c.spl~  // Infravision (spell)
			  ~spwi425.spl~ ~override/a#re0d.spl~  // Wizard Eye (spell)
	WRITE_SHORT 0x1c 2

// change spells to innates as needed
COPY_EXISTING ~spwi301.spl~ ~override/a#re05.spl~ // Clairvoyance
			  ~spwi424.spl~ ~override/a#re07.spl~ // Far sight
              ~spwi515.spl~ ~override/a#re09.spl~ // Oracle
              ~sppr701.spl~ ~override/a#re11.spl~ // Shield of the Archons
              ~spwi721.spl~ ~override/a#re14.spl~ // Mass Inisibility
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
 BUT_ONLY_IF_IT_CHANGES

COPY ~Divine_Remix/spl/a#redw0a.spl~ ~override~  // Checkmate (innate)
  SAY NAME1 @10703
  SAY NAME2 @10703
  SAY UNIDENTIFIED_DESC @10704
  SAY DESC @10704

COPY ~Divine_Remix/bam/a#redw.bam~ ~override~
COPY ~Divine_Remix/itm/a#redw00.itm~ ~override~  // Checkmate +0
  SAY NAME1 @10703
  SAY NAME2 @10703
  SAY UNIDENTIFIED_DESC @10704
  SAY DESC @10704

  SET "weap_idx" = 0

COPY_EXISTING ~a#redw00.itm~ ~override/a#redw01.itm~  // Checkmate +1
              ~a#redw00.itm~ ~override/a#redw02.itm~  // Checkmate +2
              ~a#redw00.itm~ ~override/a#redw03.itm~  // Checkmate +3
              ~a#redw00.itm~ ~override/a#redw04.itm~  // Checkmate +4
              ~a#redw00.itm~ ~override/a#redw05.itm~  // Checkmate +5
  SET "weap_idx" = ("%weap_idx%" + 1)
  WRITE_LONG  0x60 "%weap_idx%"
  WRITE_SHORT 0x86 "%weap_idx%"
  WRITE_SHORT 0x8C "%weap_idx%"
  WRITE_SHORT 0x84 (5 - "%weap_idx%")


 