COPY ~divine_remix/2da/a#shar.2da~ ~override~

ACTION_IF FILE_EXISTS_IN_GAME ~viconia.bcs~ THEN BEGIN

  COPY_EXISTING ~viconia.bcs~ ~override~
    DECOMPILE_AND_PATCH BEGIN
      REPLACE_TEXTUALLY ~ForceSpellRES("cdshar2",Myself)~ ~ForceSpellRES("a#sha0b",Myself)~
    END

END

COPY ~divine_remix/spl/trshar4.spl~ ~override~  // darkbolt
  SAY NAME1 @10610
  SAY UNIDENTIFIED_DESC @10611

COPY ~divine_remix/spl/trshar3.spl~ ~override~  // Armor of Darkness
  SAY NAME1 @10606
  SAY UNIDENTIFIED_DESC @10607

COPY ~divine_remix/itm/trshar4.itm~ ~override~  // darkbolt
  SAY NAME1 @10621
  SAY NAME2 @10621
  SAY UNIDENTIFIED_DESC @10624
  SAY DESC @10624

COPY ~divine_remix/spl/givespell.spl~ ~override/tr#shar3.spl~  // Give Armor of Darkness, lv3 Spell
  LPF ALTER_EFFECT STR_VAR resource = "trshar3" END
COPY ~divine_remix/spl/givespell.spl~ ~override/tr#shar4.spl~  // Give darkbolt, lv4 Spell
  LPF ALTER_EFFECT STR_VAR resource = "trshar4" END
 
// change spells to innates as needed
COPY_EXISTING ~spwi106.spl~ ~override/a#sha03.spl~ // Blindness
			  ~spwi220.spl~ ~override/a#sha05.spl~ // Power Word, Sleep
              ~spwi509.spl~ ~override/a#sha09.spl~ // Feeblemind
              ~spwi505.spl~ ~override/a#sha11.spl~ // shadow door
              ~spwi815.spl~ ~override/a#sha14.spl~ // Power Word, Blind
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

COPY ~Divine_Remix/bam/a#sha01.bam~ ~override~ // bams for Chakram
     ~Divine_Remix/bam/a#sha02.bam~ ~override~

COPY ~Divine_Remix/spl/a#sha0c.spl~ ~override~ // Prot. from Blindness.
  SAY NAME1 @10618
  SAY NAME2 @10618 
  
COPY ~Divine_Remix/spl/a#sha0b.spl~ ~override~  // chakram (innate)
  SAY NAME1 @10608
  SAY NAME2 @10608
  SAY UNIDENTIFIED_DESC @10609
  SAY DESC @10609

COPY ~Divine_Remix/itm/a#sha00.itm~ ~override~  // Chakram +0
  SAY NAME1 @10608
  SAY NAME2 @10608
  SAY UNIDENTIFIED_DESC @10609
  SAY DESC  @10609
  SET "weap_idx" = 0

COPY_EXISTING ~a#sha00.itm~ ~override/a#sha01.itm~  // chakram +1
              ~a#sha00.itm~ ~override/a#sha02.itm~  // chakram +2
              ~a#sha00.itm~ ~override/a#sha03.itm~  // chakram +3
              ~a#sha00.itm~ ~override/a#sha04.itm~  // chakram +4
              ~a#sha00.itm~ ~override/a#sha05.itm~  // chakram +5
  SET "weap_idx" = ("%weap_idx%" + 1)
  WRITE_LONG  0x60 "%weap_idx%"
  WRITE_SHORT 0x86 "%weap_idx%"
  WRITE_SHORT 0x8C "%weap_idx%"
  PATCH_IF ("%weap_idx%" > 2) BEGIN
    WRITE_SHORT 0x84 0
  END ELSE BEGIN
    WRITE_SHORT 0x84 (3 - "%weap_idx%")
  END

ACTION_IF GAME_IS ~tob bg2ee eet bgt~ THEN BEGIN

  COPY ~Divine_Remix/spl/a#sha71.spl~ ~override~  // Shar's Curse
    SAY NAME1 @10604
    SAY NAME2 @10604
    SAY UNIDENTIFIED_DESC @10605
    
END