/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Silverstar of Selûne                             \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Selune OR cleric_all BEGIN 

COPY ~divine_remix/bam/CDMNSHLB.bam~ ~override~ /// use spell shield BAM for moon shield

COPY ~divine_remix/spl/cdslmsd.spl~ ~override~  // Moon Shield (innate spell)
  // temp to get some strings into the game
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @10322
      READ_LONG NAME1 bio
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END
  SAY NAME1 @10307
  SAY NAME2 @10307
  SAY UNIDENTIFIED_DESC @10308
  SAY DESC @10308

COPY ~divine_remix/spl/trslmnf.spl~ ~override~  // Moonfire (innate spell)
  SAY NAME1 @10310
  SAY UNIDENTIFIED_DESC @10311

// change spells to innates as needed

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/cdselune.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~cdslmsd~ // free action as 1/5
  REPLACE_TEXTUALLY ~KITBIL2~ ~trslmnf~ // moon shield as 1/10
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~CDSelune~
  ~CDSelune                0           0           1           1           0           1           0           0~
  ~CDSelune 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~CDSelune                0       0       0       0       9       0~
  ~CDSelune                0       0       0       0       0       0~
  ~CDSelune                0       0       0       0       17      0~
  ~CDSelune                0       0       0       0       15      0~
  ~CDSelune                0       0       0       1       0       0       1       1       0~
  ~CDSelune                1       0       1       1       0       1~
  ~override/cdselune.2da~
  ~K_C_D K_C_E K_C_G K_C_H K_C_HE K_C_HL K_C_HO~
  ~0x00004000     3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
  SAY @10305
  SAY @10301
  SAY @10321

LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = CDSelune
    clascolr = ~35 21 58 25 80~
END

ACTION_IF FILE_EXISTS_IN_GAME ~J#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%CDSelune%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    CDSelune
  OUTER_SPRINT symbol cdslhly
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/bam/cdislhly.bam~ ~override~ // holy symbol
  COPY ~divine_remix/bam/cdpslhly.bam~ ~override~
  COPY ~divine_remix/itm/cdslhly.itm~ ~override~
    SAY NAME1 @10319
    SAY NAME2 @10319
    SAY UNIDENTIFIED_DESC @10320
    SAY DESC @10320

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/Selune_ar0900.baf~
  EXTEND_TOP ~ar0902.bcs~   ~divine_remix/baf/Selune_ar0902.baf~
  COMPILE ~divine_remix/dlg/selune.d~

END


/////                                                  \\\\\
///// assign kits                                      \\\\\
/////                                                  \\\\\

OUTER_SET kit = "%CDSelune%" // selune
ACTION_FOR_EACH creature IN bstq007 ysselune BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%creature%.cre~ THEN BEGIN

    COPY_EXISTING ~%creature%.cre~ ~override~
      WRITE_SHORT   0x244 0
	  WRITE_SHORT   0x273 3
      WRITE_SHORT   0x246 0x4000 + "%kit%"
//    WRITE_BYTE    0x247 0x40
	  READ_SHORT NAME1 "priestG"
	  READ_BYTE 0x234 "Lv"
	  GET_STRREF priestG "name" 
	  PATCH_IF ((("%name%" STRING_COMPARE_CASE "Priest of Selune" = 0) OR  ("%name%" STRING_COMPARE_CASE "Cleric of Selune" = 0) OR ("%name%" STRING_COMPARE_CASE "Priestess of Selune" = 0)) AND ("%Lv%">=5)) BEGIN
	    SAY NAME1 @10301 // Silverstar of Selûne 
	    SAY NAME2 @10301
	  END
      BUT_ONLY

  END

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Nightcloak of Shar                               \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Shar OR cleric_all BEGIN 

// change spells to innates as needed
COPY_EXISTING ~spwi401.spl~ ~override/a#sha09.spl~ // confusion
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

COPY ~divine_remix/spl/cdshar2.spl~ ~override~  // dark bolt
  // temp to get some strings into the game
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @10620
      READ_LONG NAME1 bio
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END
  SAY NAME1 @10621
  SAY NAME2 @10621
  SAY UNIDENTIFIED_DESC @10622
  SAY DESC @10622
  LPF ALTER_EFFECT INT_VAR match_opcode = 215 timing = 0 duration = 4 STR_VAR resource = SPCRTWPN END

COPY ~divine_remix/bam/a#sha01.bam~ ~override~ // bams for darkbolt
     ~divine_remix/bam/a#sha02.bam~ ~override~

COPY ~divine_remix/itm/cdshar2.itm~ ~override~  // darkbolt
  WRITE_BYTE 0x18 (THIS BAND 0b11110011)
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 233 target = 1 parameter1 = 2 parameter2 = 109 timing = 2 END
  LPF ALTER_ITEM_HEADER INT_VAR header_type = 2 damage_type = 4 charges = 1 flag_strength = 0 END
  SAY NAME1 @10621
  SAY NAME2 @10621
  SAY UNIDENTIFIED_DESC @10622
  SAY DESC @10622

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/a#shar.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~a#sha09~ // Confusion as 1/5
  REPLACE_TEXTUALLY ~KITBIL2~ ~cdshar2~ // dark bolt as 1/10
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~A#SHAR~
  ~A#SHAR                  0           0           1           1           0           1           0           0~
  ~A#SHAR 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#SHAR	0	0	0	0	9	0~
  ~A#SHAR		0	0	0	0	0	0~
  ~A#SHAR		0	0	0	0	17	0~
  ~A#SHAR		0	0	0	0	15	0~
  ~A#SHAR		0	0	1	0	1	1	0	0	1~
  ~A#SHAR		1	0	1	1	0	1~
  ~override/a#shar.2DA~
  ~K_C_H    K_C_D   K_C_G   K_C_E   K_C_HE   K_C_HL   K_C_HO~
  ~0x00004000	3~
  ~cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @10603
  SAY @10601
  SAY @10619

LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = ~a#shar~
    clascolr = ~35 66 60 25 80~
END

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%A#SHAR%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~A#SHAR~
  OUTER_SPRINT symbol ~a#sha25~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/itm/a#sha25.itm~ ~override~  // holy symbol
    SAY NAME1 @10615
    SAY NAME2 @10615
    SAY DESC  @10616

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/Shar_ar0900.baf~
  EXTEND_TOP ~ar0904.bcs~   ~divine_remix/baf/Shar_ar0904.baf~
  COMPILE ~divine_remix/dlg/shar.d~

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Holy Strategist of the Red Knight                \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Knight OR cleric_all BEGIN 

COPY ~divine_remix/spl/a#re0b.spl~ ~override~  // Additional Attack per round (innate)
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @10716
      READ_LONG NAME1 bio
      WRITE_LONG NAME1 `0
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END

// change spells to innates as needed
COPY_EXISTING ~spwi305.spl~ ~override/a#re07.spl~ // haste
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/a#red.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~a#re07 ~ // haste as 1/5
  REPLACE_TEXTUALLY ~GA_KITBIL2~ ~****   ~ // nothing as 1/10
  SET_2DA_ENTRY 2 14 50 ~AP_a#re0b~     // extra attack
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~A#RED~
  ~A#RED                   0           0           1           1           0           1           0           0~
  ~A#RED  0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#RED 	0	0	0	0	9	0~
  ~A#RED 		0	0	0	0	0	0~
  ~A#RED 		0	0	0	0	17	0~
  ~A#RED 		0	0	0	0	15	0~
  ~A#RED 		1	1	1	0	0	0	0	0	0~
  ~A#RED 		1	0	1	1	0	1~
  ~override/a#red.2da~
  ~K_C_H    K_C_D   K_C_G   K_C_E   K_C_HE   K_C_HL   K_C_HO~
  ~0x00004000 3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @10714
  SAY @10701
  SAY @10715
  
LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = ~a#red~
    clascolr = ~35 63 47 25 80~
END

  
ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%A#RED%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~A#RED~
  OUTER_SPRINT symbol ~a#red25~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/bam/cdirdhly.bam~ ~override~ // holy symbol
  COPY ~divine_remix/bam/cdprdhly.bam~ ~override~
  COPY ~divine_remix/itm/a#red25.itm~  ~override~
    SAY NAME1 @10710
    SAY NAME2 @10710
    SAY DESC  @10711

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/red_ar0900.baf~
  EXTEND_TOP ~ar0901.bcs~   ~divine_remix/baf/red_ar0901.baf~
  COMPILE ~divine_remix/dlg/red.d~

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Battleguard of Tempus                            \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Tempus OR cleric_all BEGIN 

// change spells to innates as needed
COPY_EXISTING ~sppr412.spl~ ~override/a#tem07.spl~ // holy power
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/a#temp.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~a#tem07~ // Holy Power as 1/5
  REPLACE_TEXTUALLY ~KITBIL2~ ~spcl321~ // enrage as 1/10
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~A#TEMP~
  ~A#TEMP                  0           0           1           1           0           1           0           0~
  ~A#TEMP 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 2 2 0 0 2 2 2 0 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#TEMP	        0       0       0       0       9       0~
  ~A#TEMP		0	0	0	0	0	0~
  ~A#TEMP		0	0	0	0	17	0~
  ~A#TEMP		0	0	0	0	15	0~
  ~A#TEMP		0	0	0	0	0	0	1	1	1~
  ~A#TEMP		1	0	1	1	0	1~
  ~override/a#temp.2da~
  ~K_C_H    K_C_D   K_C_G   K_C_E   K_C_HE   K_C_HL   K_C_HO~
  ~0x00004000	3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @10914
  SAY @10901
  SAY @10915
  
LAF fl#add_kit_ee
  STR_VAR
    kit_name = ~a#temp~
    clascolr = ~80 126 127 93 97~
    clswpbon = ~1 0 3~
END

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%A#TEMP%")
    FOR (row = 2; row < 25 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~2~
    END
    SET_2DA_ENTRY_LATER ~aoe~ 4 column ~0~
    SET_2DA_ENTRY_LATER ~aoe~ 9 column ~0~
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~A#temp~
  OUTER_SPRINT symbol ~a#tem25~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/bam/cditmhly.bam~ ~override~ // holy symbol
  COPY ~divine_remix/bam/cdptmhly.bam~ ~override~
  COPY ~divine_remix/itm/a#tem25.itm~  ~override~
    SAY NAME1 @10910
    SAY NAME2 @10910
    SAY UNIDENTIFIED_DESC @10911
    SAY DESC @10911

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/tempus_ar0900.baf~
  EXTEND_TOP ~ar0902.bcs~   ~divine_remix/baf/tempus_ar0904.baf~
  COMPILE ~divine_remix/dlg/tempus.d~

END

/////                                                  \\\\\
///// assign kits                                      \\\\\
/////                                                  \\\\\

OUTER_SET kit = "%A#TEMP%" // tempus
ACTION_FOR_EACH creature IN kpchap01 everard accalia BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%creature%.cre~ THEN BEGIN

    COPY_EXISTING ~%creature%.cre~ ~override~
      WRITE_SHORT   0x244 0
      WRITE_SHORT   0x246 0x4000 + "%kit%"
//    WRITE_BYTE    0x247 0x40
	  READ_SHORT NAME1 "priestG"
	  READ_BYTE 0x234 "Lv"
	  GET_STRREF priestG "name" 
	  PATCH_IF ((("%name%" STRING_COMPARE_CASE "Priest of Tempus" = 0) OR  ("%name%" STRING_COMPARE_CASE "Cleric of Tempus" = 0) OR  ("%name%" STRING_COMPARE_CASE "Priestess of Tempus" = 0)) AND ("%Lv%">=5)) BEGIN
	  SAY NAME1 @10191 //Battleguard of Tempus 
	  SAY NAME2 @10191
	  END
      BUT_ONLY

  END

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Painbearer of Ilmater                            \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Ilmater OR cleric_all BEGIN 

COPY ~divine_remix/bam/cdilenda.bam~ ~override~ // Ilmater's Endurance (innate)
     ~divine_remix/bam/cdilendb.bam~ ~override~
     ~divine_remix/bam/cdilendc.bam~ ~override~
COPY ~divine_remix/spl/cdilend.spl~  ~override~
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @11211
      READ_LONG NAME1 bio
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END
  SAY NAME1 @11205
  SAY NAME2 @11205
  SAY UNIDENTIFIED_DESC @11206
  SAY DESC @11206

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/cdilmatr.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~SPCL211~ // lay on hands as 1/5
  REPLACE_TEXTUALLY ~KITBIL2~ ~cdilend~ // ilmater's endurance as 1/10
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~CDILMATR~
  ~CDILMATR                  0           0           1           1           0           1           0           0~
  ~CDILMATR 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~CDILMATR	0	0	0	0	9	0~
  ~CDILMATR		0	0	0	0	0	0~
  ~CDILMATR		0	0	0	0	17	0~
  ~CDILMATR		0	0	0	0	15	0~
  ~CDILMATR		1	1	0	1	0	0	0	0	0~
  ~CDILMATR		1	0	1	1	0	1~
  ~override/cdilmatr.2da~
  ~K_C_H    K_C_D   K_C_G   K_C_E   K_C_HE   K_C_HL   K_C_HO~
  ~0x00004000	3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @11209
  SAY @11201
  SAY @11210
  
LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = ~cdilmatr~
    clascolr = ~35 67 67 25 80~
END

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%CDILMATR%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~CDILMATR~
  OUTER_SPRINT symbol ~cdilhly~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/bam/cdiilhly.bam~ ~override~ // holy symbol
  COPY ~divine_remix/bam/cdpilhly.bam~ ~override~
  COPY ~divine_remix/itm/cdilhly.itm~  ~override~
    SAY NAME1 @11207
    SAY NAME2 @11207
    SAY UNIDENTIFIED_DESC @11208
    SAY DESC @11208

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/ilmater_ar0900.baf~
  EXTEND_TOP ~ar0901.bcs~   ~divine_remix/baf/ilmater_ar0901.baf~
  EXTEND_TOP ~ar0902.bcs~   ~divine_remix/baf/ilmater_ar0902.baf~
  COMPILE ~divine_remix/dlg/ilmater.d~

END

/////                                                  \\\\\
///// assign kits                                      \\\\\
/////                                                  \\\\\

OUTER_SET kit = "%CDILMATR%" // ilmater
ACTION_FOR_EACH creature IN _priilm _priilmu priilm priilmu slilmat wilmat s#ilmat1 ja#pill1 BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%creature%.cre~ THEN BEGIN

    COPY_EXISTING ~%creature%.cre~ ~override~
      WRITE_SHORT   0x244 0
      WRITE_SHORT   0x246 0x4000 + "%kit%"
//    WRITE_BYTE    0x247 0x40
	  READ_SHORT NAME1 "priestG"
	  READ_BYTE 0x234 "Lv"
	  GET_STRREF priestG "name" 
	  PATCH_IF ((("%name%" STRING_COMPARE_CASE "Priest of Ilmater" = 0) OR  ("%name%" STRING_COMPARE_CASE "Cleric of Ilmater" = 0) OR  ("%name%" STRING_COMPARE_CASE "Priestess of Ilmater" = 0)) AND ("%Lv%">=5)) BEGIN
	  SAY NAME1 @11201 // Painbearer of Ilmater  
	  SAY NAME2 @11201 
	  END
      BUT_ONLY

  END

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Firewalker of Kossuth kit                        \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Kossuth OR cleric_all BEGIN 

COPY ~divine_remix/spl/a#kos0c.spl~ ~override~
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @11511
      READ_LONG NAME1 bio
      WRITE_LONG 0x08 `0
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END

// change spells to innates as needed
COPY_EXISTING ~spwi523.spl~ ~override/a#kos09.spl~ // sunfire
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/a#koss.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~a#kos09~ // Sunfire as 1/5
  FOR (index = 1 ; index < 51 ; ++index) BEGIN
    SET_2DA_ENTRY 2 index 50 ~AP_a#kos0c~
  END
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~A#KOSS~
  ~A#KOSS                  0           0           1           1           0           1           0           0~
  ~A#KOSS   0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#KOSS	0	0	0	0	9	0~
  ~A#KOSS		0	0	0	0	0	0~
  ~A#KOSS		0	0	0	0	17	0~
  ~A#KOSS		0	0	0	0	15	0~
  ~A#KOSS		0	1	1	0	1	0	0	0	0~
  ~A#KOSS		1	0	1	1	0	1~
  ~override/a#koss.2da~
  ~K_C_G   K_C_E   K_C_HE~
  ~0x40000000	3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @11509
  SAY @11503
  SAY @11510
  
LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = ~a#koss~
    clascolr = ~35 46 47 25 80~
END

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%A#KOSS%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~a#koss~
  OUTER_SPRINT symbol ~a#koss25~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/bam/a#ikos25.bam~ ~override~ // holy symbol
  COPY ~divine_remix/bam/a#pkos25.bam~ ~override~
  COPY ~divine_remix/itm/a#koss25.itm~ ~override~
    SAY NAME1 @11507
    SAY NAME2 @11507
    SAY UNIDENTIFIED_DESC @11508
    SAY DESC @11508

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/kossuth_ar0900.baf~
  EXTEND_TOP ~ar0901.bcs~   ~divine_remix/baf/kossuth_ar0901.baf~
  EXTEND_TOP ~ar0902.bcs~   ~divine_remix/baf/kossuth_ar0902.baf~
  EXTEND_TOP ~ar0904.bcs~   ~divine_remix/baf/kossuth_ar0904.baf~
  COMPILE ~divine_remix/dlg/kossuth.d~

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Authlim of Iyachtu Xvim                          \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Iyachtu OR cleric_all BEGIN 

COPY ~divine_remix/spl/CDXVFEAR.spl~ ~override~  // immunity to fear (permanent innate spell)
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @11811
      READ_LONG NAME1 bio
      WRITE_LONG 0x08 `0
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END

// change spells to innates as needed
COPY_EXISTING ~spwi412.spl~ ~override/cdxvgml.spl~ // greater malison (innate)
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~spwi412.spl~ ~override~ // make innate/arcane GMs unstackable
  LPF CLONE_EFFECT STR_VAR match_resource = spwi412 resource = cdxvgml insert = above END // picks up 321 for ee games, 206 for non-ee

COPY_EXISTING ~cdxvgml.spl~ ~override~ // make innate/arcane GMs unstackable
  LPF CLONE_EFFECT STR_VAR match_resource = spwi412 resource = cdxvgml insert = below END // picks up 321 for ee games, 206 for non-ee

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/cdxvim.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~cdxvgml~ // greater malison as 1/5
  REPLACE_TEXTUALLY ~ABILITY2    GA_KITBIL2 ~ ~ABILITY2    AP_CDXVFEAR~ // no 1/10
  REPLACE_TEXTUALLY ~GA_KITBIL2~ ~****      ~ // no 1/10
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~CDXvim~
  ~CDXvim                  0           0           1           1           0           1           0           0~
  ~CDXvim   0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~CDXvim                  0       0       0       0       9       0~
  ~CDXvim                  0       0       0       0       0       0~
  ~CDXvim                  0       0       0       0       17      0~
  ~CDXvim                  0       0       0       0       15      0~
  ~CDXvim                  0       1       1       0       0       1       0       0       0~
  ~CDXvim                  1       0       1       1       0       1~
  ~override/cdxvim.2da~
  ~K_C_D K_C_E K_C_G K_C_H K_C_HE K_C_HL K_C_HO~
  ~0x00004000     3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
  SAY @11809
  SAY @11801
  SAY @11810

LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = ~cdxvim~
    clascolr = ~35 52 66 25 80~
END

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%CDXvim%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~CDXvim~
  OUTER_SPRINT symbol ~cdxvhly~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/bam/cdixvhly.bam~ ~override~ // holy symbol
       ~divine_remix/bam/cdpxvhly.bam~ ~override~
  COPY ~divine_remix/itm/cdxvhly.itm~  ~override~
    SAY NAME1 @11803
    SAY NAME2 @11803
    SAY UNIDENTIFIED_DESC @11804
    SAY DESC @11804

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/xvim_ar0900.baf~
  EXTEND_TOP ~ar0901.bcs~   ~divine_remix/baf/xvim_ar0901.baf~
  COMPILE ~divine_remix/dlg/xvim.d~

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Lorekeeper of Oghma kit                          \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Oghma OR cleric_all BEGIN 

// change spells to innates as needed
COPY_EXISTING ~spwi419.spl~ ~override/a#og07.spl~ // secret word
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

COPY ~divine_remix/spl/a#og0b.spl~ ~override~  // Lore boost (innate)
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @12109
      READ_LONG NAME1 bio
      WRITE_LONG 0x08 `0
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/a#ogma.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~a#og07~ // secret word as 1/5
  FOR (index = 1 ; index < 51 ; ++index) BEGIN
    SET_2DA_ENTRY 2 index 50 ~AP_a#og0b~
  END
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~A#OGMA~
  ~A#OGMA                  0           0           1           1           0           1           0           0~
  ~A#OGMA 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#OGMA	0	0	0	0	9	0~
  ~A#OGMA		0	0	0	0	0	0~
  ~A#OGMA		0	0	0	0	17	0~
  ~A#OGMA		0	0	0	0	15	0~
  ~A#OGMA		1	1	1	1	1	1	1	1	1~
  ~A#OGMA		1	0	1	1	0	1~
  ~override/a#ogma.2da~
  ~K_C_H    K_C_D   K_C_G   K_C_E   K_C_HE   K_C_HL   K_C_HO~
  ~0x00004000 3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @12107
  SAY @12101
  SAY @12108

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%A#OGMA%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END

LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = ~a#ogma~
    clascolr = ~35 66 66 25 80~
END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~a#ogma~
  OUTER_SPRINT symbol ~a#og25~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/bam/cdioghly.bam~   ~override~ // holy symbol
       ~divine_remix/bam/cdpoghly.bam~   ~override~
  COPY ~divine_remix/itm/a#koss25.itm~ ~override/a#og25.itm~// This is ok because they have the same alignment restrictions... Yeh.
    SAY NAME1 @12105
    SAY NAME2 @12105
    SAY UNIDENTIFIED_DESC @12106
    SAY DESC @12106
    WRITE_ASCII 0x3a ~cdioghly~
    WRITE_ASCII 0x58 ~cdpoghly~

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/oghma_ar0900.baf~
  EXTEND_TOP ~ar0901.bcs~   ~divine_remix/baf/oghma_ar0901.baf~
  EXTEND_TOP ~ar0902.bcs~   ~divine_remix/baf/oghma_ar0902.baf~
  EXTEND_TOP ~ar0904.bcs~   ~divine_remix/baf/oghma_ar0904.baf~
  COMPILE ~divine_remix/dlg/oghma.d~

END

/////                                                  \\\\\
///// assign kits                                      \\\\\
/////                                                  \\\\\

OUTER_SET kit = "%A#OGMA%" // oghma
ACTION_FOR_EACH creature IN doghma poghm10 poghm3 poghm6 poghm8 poghm9 poghma poghma3 poghma4 poghma5 poghma6 poghma7 poghma8 _poghm10 _poghm3 _poghm6 _poghm8 _poghm9 _poghma _poghma3 _poghma4 _poghma5 _poghma6 _poghma7 _poghma8 ja#oghm1 BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%creature%.cre~ THEN BEGIN

    COPY_EXISTING ~%creature%.cre~ ~override~
      WRITE_SHORT   0x244 0
      WRITE_SHORT   0x246 0x4000 + "%kit%"
//    WRITE_BYTE    0x247 0x40
      READ_SHORT NAME1 "priestG"
	  READ_BYTE 0x234 "Lv"
	  GET_STRREF priestG "name" 
	  PATCH_IF ((("%name%" STRING_COMPARE_CASE "Priest of Oghma" = 0) OR  ("%name%" STRING_COMPARE_CASE "Cleric of Oghma" = 0) OR  ("%name%" STRING_COMPARE_CASE "Priestess of Oghma" = 0)) AND ("%Lv%">=3)) BEGIN
	  SAY NAME1 @12101  //Lorekeeper of Oghma
	  SAY NAME2 @12101 
	  END
	  BUT_ONLY

  END

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Heartwarder of Sune kit                          \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Sune OR cleric_all BEGIN 

// change spells to innates as needed
COPY_EXISTING ~spwi411.spl~ ~override/nmsun07.spl~ // emotion
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES
COPY ~divine_remix/spl/nmsun0A.spl~ ~override~ //+1 Charisma 
COPY ~divine_remix/spl/cdsune2.spl~ ~override~
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @12411
      READ_LONG NAME1 bio
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END
  SAY NAME1 @12409
  SAY NAME2 @12409
  SAY UNIDENTIFIED_DESC @12410
  SAY DESC @12410

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/nmsune.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~nmsun07~ // emotion as 1/5
  REPLACE_TEXTUALLY ~KITBIL2~ ~cdsune2~ // Veil of Djalice as 1/10
  INSERT_2DA_ROW 3 50 ~ABILITY3    AP_nmsun0A  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****~//+1 charisma
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~NMSUNE~
  ~NMSUNE                0           0           1           1           0           1           0           0~
  ~NMSUNE 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~NMSUNE                0       0       0       0       9       0~
  ~NMSUNE                0       0       0       0       0       0~
  ~NMSUNE                0       0       0       0       17      0~
  ~NMSUNE                0       0       0       0       15      0~
  ~NMSUNE                0       0       0       1       0       0       1       1       0~
  ~NMSUNE                1       0       1       1       0       1~
  ~override/nmsune.2da~
  ~K_C_E K_C_HE~
  ~0x00004000	3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @12407
  SAY @12401
  SAY @12408

LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = ~NMSUNE~
    clascolr = ~35 49 46 25 80~
END

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%NMSUNE%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~NMSUNE~
  OUTER_SPRINT symbol ~nmsuhly~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/bam/nmisuhly.bam~ ~override~ // holy symbol
  COPY ~divine_remix/bam/nmpsuhly.bam~ ~override~
  COPY ~divine_remix/itm/nmsuhly.itm~  ~override~
    SAY NAME1 @12405
    SAY NAME2 @12405
    SAY UNIDENTIFIED_DESC @12406
    SAY DESC @12406

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~Divine_Remix/baf/sune_ar0900.baf~
  EXTEND_TOP ~ar0902.bcs~   ~Divine_Remix/baf/sune_ar0902.baf~
  COMPILE ~Divine_Remix/dlg/sune.d~

END
/////                                                  \\\\\
///// assign kits                                      \\\\\
/////                                                  \\\\\

OUTER_SET kit = "%NMSUNE%" // sune
ACTION_FOR_EACH creature IN isnfxps /*YxYve1*/ BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%creature%.cre~ THEN BEGIN

    COPY_EXISTING ~%creature%.cre~ ~override~
      WRITE_SHORT   0x244 0
      WRITE_SHORT   0x246 0x4000 + "%kit%"
//    WRITE_BYTE    0x247 0x40
	  READ_SHORT NAME1 "priestG"
	  READ_BYTE 0x234 "Lv"
	  GET_STRREF priestG "name" 
	  PATCH_IF ((("%name%" STRING_COMPARE_CASE "Priest of Sune" = 0) OR  ("%name%" STRING_COMPARE_CASE "Cleric of Sune" = 0) OR  ("%name%" STRING_COMPARE_CASE "Priestess of Sune" = 0)) AND ("%Lv%">=5)) BEGIN
	  SAY NAME1 @12401 //Heartwarder of Sune 
	  SAY NAME2 @12401
	  END
      BUT_ONLY

  END

END

ACTION_IF FILE_EXISTS_IN_GAME ~YxYve1.cre~ THEN BEGIN
	
	  COPY_EXISTING ~yxyve.bcs~ 	override
	  DECOMPILE_AND_PATCH BEGIN
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH ~AddKit(yxkit)~ ~AddKit(nmsune)~
	  END	
    BUT_ONLY
	
	EXTEND_BOTTOM ~yxyve.bcs~   ~divine_remix/baf/yxyve.baf~

	  COPY_EXISTING ~YxYv25.bcs~ 	override
	  DECOMPILE_AND_PATCH BEGIN
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH ~LevelGT(Myself,22)~ 
~HasItem("NMSUHLY",Myself)~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH ~GiveItemCreate("YxSymb",Myself,0,0,0)~ 
~GiveItemCreate("YxSymb",Myself,0,0,0)
		DestroyItem("NMSUHLY")~
	  END	
    BUT_ONLY

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Feywarden of Corellon kit                        \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Corellon OR cleric_all BEGIN 

//save vs.death bonus
COPY ~divine_remix/spl/a#fey0a.spl~ ~override~
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @12710
      READ_LONG NAME1 bio
      WRITE_LONG NAME1 `0
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END

// change spells to innates as needed
COPY_EXISTING ~spwi510.spl~ ~override/a#fey09.spl~ // spell immunity
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/a#feyw.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~a#fey09~ // Spell Immunity as 1/5
  REPLACE_TEXTUALLY ~GA_KITBIL2~ ~****   ~ // nothing as 1/10
  SET_2DA_ENTRY 2 1 50 ~AP_a#fey0a~     // save bonus
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~A#FEYWARDEN~
  ~A#FEYWARDEN                0           0           1           1           0           1           0           0~
  ~A#FEYWARDEN 0 0 0 0 2 2 0 2 0 0 0 0 0 0 0 0 2 2 0 0 2 2 2 0 0 0 0 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#FEYWARDEN                0       0       0       0       9       0~
  ~A#FEYWARDEN                0       0       0       0       0       1~
  ~A#FEYWARDEN                0       0       0       0       17      0~
  ~A#FEYWARDEN                0       0       0       0       15      0~
  ~A#FEYWARDEN                1       0       1       1       0       1       1       1       0~
  ~A#FEYWARDEN                1       0       1       1       0       1~
  ~override/a#feyw.2da~
  ~K_C_E K_C_HE~
  ~0x00004000	3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @12701
  SAY @12702
  SAY @12709

LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = ~A#FEYWARDEN~
    clascolr = ~35 21 57 25 80~
END

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%A#FEYWARDEN%")
    FOR (row = 2; row < 25 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~2~
    END
    SET_2DA_ENTRY_LATER ~aoe~ 4 column ~0~
    SET_2DA_ENTRY_LATER ~aoe~ 9 column ~0~
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~A#FEYWARDEN~
  OUTER_SPRINT symbol ~a#feyhly~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/bam/a#feyhly.bam~ ~override~ // holy symbol
  COPY ~divine_remix/itm/a#feyhly.itm~ ~override~
    SAY NAME1 @12707
    SAY NAME2 @12707
    SAY UNIDENTIFIED_DESC @12708
    SAY DESC @12708

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/Corellon_ar0900.baf~
  EXTEND_TOP ~ar0902.bcs~   ~divine_remix/baf/Corellon_ar0902.baf~
  COMPILE ~divine_remix/dlg/corellon.d~

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Strifeleader of Cyric kit                        \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Cyric OR cleric_all BEGIN 

//Dread Blast innate
COPY ~divine_remix/spl/a#cyr07.spl~ ~override~
  PATCH_IF ((GAME_IS ~bgee bg2ee eet~) OR (FILE_EXISTS_IN_GAME ~howparty.2da~)) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~howparty.2da~ BEGIN // iwdee
      SAY NAME1 @13011
      READ_LONG NAME1 bio
    END ELSE BEGIN // bgee/bg2ee bio
      PATCH_IF GAME_IS ~bg2ee eet~ BEGIN // bg2ee
        SET bio = "-1"
      END ELSE BEGIN // bgee
        SET bio  = 15884
      END
    END
  END
  SAY NAME1 @13000
  SAY NAME2 @13000
  SAY 0x50 @13010
  SAY 0x54 @13010

// build 2da from generic ability schedule
COPY ~divine_remix/2da/generic.2da~ ~override/a#cyric.2da~
  REPLACE_TEXTUALLY ~KITBIL1~ ~SPCL423~ // poison weapon as 1/5
  REPLACE_TEXTUALLY ~KITBIL2~ ~a#cyr07~ // dread blast as 1/10
  PATCH_IF NOT FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN
    REPLACE_TEXTUALLY ~AP_CDHLYSYM~ ~****       ~
  END

ADD_KIT ~A#CYRIC~
  ~A#CYRIC                  0           0           1           1           0           1           0           0~
  ~A#CYRIC 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#CYRIC	        0       0       0       0       9       0~
  ~A#CYRIC		0	0	0	0	0	0~
  ~A#CYRIC		0	0	0	0	17	0~
  ~A#CYRIC		0	0	0	0	15	0~
  ~A#CYRIC		0	0	1	0	0	1	0	1	1~
  ~A#CYRIC		1	0	1	1	0	1~
  ~override/a#cyric.2da~
  ~K_C_H    K_C_D   K_C_G   K_C_E   K_C_HE   K_C_HL   K_C_HO~
  ~0x00004000	3~
  ~Cl0~
  ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @13002
  SAY @13003
  SAY @13009

LAF fl#add_kit_ee
  INT_VAR
    biography = bio
  STR_VAR
    kit_name = ~A#CYRIC~
    clascolr = ~35 67 67 25 80~
END

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%A#CYRIC%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF FILE_CONTAINS_EVALUATED (~clabpr02.2da~ ~AP_CDHLYSYM~) THEN BEGIN // holy symbols

  OUTER_SPRINT kit    ~A#CYRIC~
  OUTER_SPRINT symbol ~a#cyr25~
  OUTER_FOR (index = 1 ; index < 7 ; ++index) BEGIN

    EXTEND_TOP ~baldur.bcs~   ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER
    EXTEND_TOP ~baldur25.bcs~ ~divine_remix/baf/holysym.baf~ EVALUATE_BUFFER

  END

  COPY ~divine_remix/itm/a#cyr25.itm~ ~override~
    SAY NAME1 @13005
    SAY NAME2 @13005
    SAY UNIDENTIFIED_DESC @13006
    SAY DESC @13006

END

/////                                                  \\\\\
///// Stronghold fixes                                 \\\\\
/////                                                  \\\\\

ACTION_IF GAME_IS ~soa bg2 tob bg2ee eet bgt~ THEN BEGIN // temple stronghold stuff

  ACTION_IF GAME_IS ~tob bg2ee eet bgt~ THEN BEGIN //Compile dialogue alteration for Cyric in the Pocket Plane

    COMPILE ~divine_remix/dlg/cyricpp.d~

  END

  EXTEND_TOP ~ar0900.bcs~   ~divine_remix/baf/cyric_ar0900.baf~
  EXTEND_TOP ~ar0902.bcs~   ~divine_remix/baf/cyric_ar0904.baf~
  COMPILE ~divine_remix/dlg/cyric.d~

END

/////                                                  \\\\\
///// assign kits                                      \\\\\
/////                                                  \\\\\

OUTER_SET kit = "%A#CYRIC%" // cyric
ACTION_FOR_EACH creature IN ar18prie hghprmod mvpries prcdmod prcmod slapri Z#pri1 Z#pri2 dcleric O#Tiax O#Tiax25 pptiax pptiax2 tiax tiax4 tiax6 dot#tiax lamalh bassil mulahe BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%creature%.cre~ THEN BEGIN

    COPY_EXISTING ~%creature%.cre~ ~override~
      WRITE_SHORT   0x244 0
      WRITE_SHORT   0x246 0x4000 + "%kit%"
//    WRITE_BYTE    0x247 0x40
	  READ_SHORT NAME1 "priestG"
	  READ_BYTE 0x234 "Lv"
	  GET_STRREF priestG "name" 
	  PATCH_IF ((("%name%" STRING_COMPARE_CASE "Priest of Cyric" = 0) OR  ("%name%" STRING_COMPARE_CASE "Cleric of Cyric" = 0) OR  ("%name%" STRING_COMPARE_CASE "Priestess of Cyric" = 0)) AND ("%Lv%">=5)) BEGIN
	  SAY NAME1 @13003 //Strifeleader of Cyric 
	  SAY NAME2 @13003
	  END      
	  BUT_ONLY

  END

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Oozemaster Druid kit                             \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Oozemaster OR druid_all BEGIN 
//Paralytic Touch
COPY_EXISTING ~spwi218.spl~ ~override/a#ooze1.spl~ //Ghoul Touch
  SAY NAME1 @20305
  SAY NAME2 @20305
  READ_LONG  0x64 "abil_off" ELSE 0
  READ_SHORT 0x68 "abil_num" ELSE 0
  READ_LONG  0x6A "fx_off" ELSE 0
  READ_ASCII ("%abil_off%" + 0x04) "bam" (8) // reads the bam filename from ability
  WRITE_SHORT 0x1C 4                         // sets spell type to innate (4)
  WRITE_LONG  0x34 1                         // sets spell level to 1 to avoid scripting issues
  WRITE_EVALUATED_ASCII 0x3A "%bam%" #8      // writes the bam filename from abilities to spell icon
  FOR ( index = 0 ; index < abil_num ; index = index + 1 ) BEGIN
    WRITE_SHORT ("%abil_off%" + 0x02 + (0x28 * "%index%")) 4 // changes ability icon location to innate (4)
    READ_SHORT  ("%abil_off%" + 0x12 + (0x28 * "%index%")) "speed" // reads casting speed
    PATCH_IF ("%speed%" > 3) BEGIN
      WRITE_SHORT  ("%abil_off%" + 0x12 + (0x28 * "%index%")) ("%speed%" - 2) // reduces casting speed
    END ELSE BEGIN
      WRITE_SHORT  ("%abil_off%" + 0x12 + (0x28 * "%index%")) 0 // makes instant
    END
    READ_SHORT  ("%abil_off%" + 0x1e + (0x28 * "%index%")) "abil_fx_num" ELSE 0
    READ_SHORT  ("%abil_off%" + 0x20 + (0x28 * "%index%")) "abil_fx_idx" ELSE 0
    FOR ( index2 = 0 ; index2 < abil_fx_num ; index2 = index2 + 1 ) BEGIN // loops through and changes item created
      READ_SHORT ("%fx_off%" +        (0x30 * ("%abil_fx_idx%" + "%index2%" - 1))) "opcode" ELSE 0
      READ_ASCII ("%fx_off%" + 0x14 + (0x30 * ("%abil_fx_idx%" + "%index2%" - 1))) "item" ELSE 0
      PATCH_IF (("%opcode%" = 111) AND ("%item%" STRING_COMPARE_CASE "ghoult" = 0)) BEGIN
        WRITE_ASCII ("%fx_off%" + 0x14 + (0x30 * ("%abil_fx_idx%" + "%index2%" - 1))) ~a#oozet~ #8
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES

//Renaming called item
COPY_EXISTING ~ghoult.itm~ ~override/a#oozet.itm~
  SAY NAME1 @20305
  SAY NAME2 @20305

//Shapeshift to mustard jelly
COPY ~divine_remix/spl/a#ooze3.spl~ ~override~
  SAY NAME1 @20306
  SAY NAME2 @20306

// shapeshift to nat form
COPY ~divine_remix/spl/a#ooze3a.spl~ ~override~

COPY ~divine_remix/spl/a#ooze2.spl~ ~override~ //immune to poison
     ~divine_remix/spl/a#ooze5.spl~ ~override~ //immune to disease
     ~divine_remix/spl/a#ooze6.spl~ ~override~ //immune to blindness, sleep, paralysis, stunning and critical hits
     ~divine_remix/spl/a#ooze7.spl~ ~override~ //charisma drop
  SAY NAME1 @20307
  SAY NAME2 @20307
COPY ~divine_remix/spl/a#ooze4.spl~ ~override~ //immune to acid
  LPF ALTER_EFFECT INT_VAR resist_dispel = 0 END
  SAY NAME1 @20308
  SAY NAME2 @20308


ADD_KIT ~A#OOZE~
  ~A#OOZE                  0           0           1           1           0           1           0           0~
  ~A#OOZE 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#OOZE	0	0	0	0	12	7~
  ~A#OOZE		0	0	0	0	0	0~
  ~A#OOZE		0	0	0	0	17	0~
  ~A#OOZE		0	0	0	0	15	0~
  ~A#OOZE		0	1	0	1	1	1	0	1	0~
  ~A#OOZE		1	0	0	0	0	0~
  ~divine_remix/2da/a#ooze.2da~
  ~K_D_H    K_D_D   K_D_G   K_D_E   K_D_HE   K_D_HL   K_D_HO~
  ~0x00004000 11~
  ~dr0~
  ~LEAT20 * HELM19 BAG27 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @20302
  SAY @20303
  SAY @20304

LAF fl#add_kit_ee
  STR_VAR
    kit_name = ~A#OOZE~
    clascolr = ~35 67 67 25 80~
END

ACTION_IF FILE_EXISTS_IN_GAME ~j#aoev22.txt~ THEN BEGIN // if Ashes of Embers is installed

  COPY_EXISTING ~weapprof.2da~ ~override~
    SET "column" = (22 + "%A#OOZE%")
    FOR (row = 2; row < 35 ; row = row + 1) BEGIN
      SET_2DA_ENTRY_LATER ~aoe~ row column ~1~
    END
    SET_2DA_ENTRIES_NOW ~aoe~ 1
    BUT_ONLY_IF_IT_CHANGES

END
END

/////                                                  \\\\\
///// assign kits                                      \\\\\
/////                                                  \\\\\

ACTION_FOR_EACH creature IN a#murn BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%creature%.cre~ THEN BEGIN

  ADD_KIT ~A#OOZ2~
	  ~A#OOZE                  0           0           1           1           0           1           0           0~
	  ~A#OOZE 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	  ~A#OOZE	0       0       0       0       9       0~
	  ~A#OOZE		0       0       0       0       0       0~
	  ~A#OOZE		0	0	0	0	17	0~
	  ~A#OOZE		0	0	0	0	15	0~
	  ~A#OOZE		0       0       0       1       0       0       1       1       0~
	  ~A#OOZE		1       0       1       1       0       1~
	  ~divine_remix/2da/a#ooze.2da~
	  ~~
	  ~0x00004000 3~
	  ~Cl0~
	  ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
	  SAY @20302
	  SAY @20303
	  SAY @20304

OUTER_SET kit = "%A#OOZ2%" // Oozemaster

    COPY_EXISTING ~%creature%.cre~ ~override~
      WRITE_SHORT   0x244 0
      WRITE_SHORT   0x246 0x4000 + "%kit%" // Oozemaster
	  WRITE_BYTE   0x273 11 // Druid
//    WRITE_BYTE    0x247 0x40
	  BUT_ONLY

  END

END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Bowslinger                                       \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Bowslinger OR druid_all BEGIN 

ADD_KIT NMRNBSLN // ROWNAME in KITLIST.2da
  ~NMRNBSLN                1           1           1           1           1           1           1           1~ // CLASWEAP.2DA (weapons class can use)
  ~NMRNBSLN 1 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 4 4 4 2 2 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~ // WEAPPROF (proficiency points this kit can place)
  ~NMRNBSLN                13      13      14      0       14      15~ // ABCLASRQ.2da (minimum stats)
  ~NMRNBSLN                0       0       0       0       0       0~ // ABCLSMOD.2da (stat modifiers)
  ~NMRNBSLN                17      17      0       0       17      0~ // ABDCDSRQ.2da (minimum stats needed to dual-class from this class)
  ~NMRNBSLN                15      15      0       0       15      0~ // ABDCSCRQ.2da (minimum stats needed to dual-class to this class)
  ~NMRNBSLN                1       0       0       1       0       0       1       0       0~ // ALIGNMNT.2da (alignments this kit can be)
  ~NMRNBSLN                0       1       0       0       0       0~ // DUALCLAS.2da (classes this kit can be dualed with)
  ~divine_remix/2da/nmrnbsln.2da~ // CLAB****.2da (abilities file)
  ~K_R_E K_R_HE~ // K_B_H.2da, K_B_HE.2da, etc (class/race restrictions)
  ~0x00008000 12~ // UNUSABLE in KITLIST.2da (item restriction flag this kit uses)
  ~Ra0~ // LuBa0.2da, LuBa1.2da, etc (high level abilities file)
  ~LEAT20 DART03,40 HELM07 BAG26 RING06 RING31 CLCK27 BOOT01 AMUL19 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW11 BOW19 XBOW06~ // ToB starting equipment (PC only)
  SAY @40301 // Kit name without capitals
  SAY @40302 // Kit name with capitals
  SAY @40303 // Full kit description

LAF fl#add_kit_ee
  STR_VAR
    kit_name = ~NMRNBSLN~
    clascolr = ~35 67 67 25 80~
END

COPY ~divine_remix/spl/nmrnbs1.spl~ ~override~ // -1 to damage with melee
     ~divine_remix/spl/nmrnbs2.spl~ ~override~ // Called Shot

COPY ~divine_remix/spl/nmrnbs3.spl~ ~override~ // Speed Shot
  SAY NAME1 @40304
  SAY NAME2 @40304
  SAY UNIDENTIFIED_DESC  @40305
  SAY DESC  @40305

// change spells to innates as needed
COPY_EXISTING ~spwi203.spl~ ~override/nmrnbs4.spl~ // detect invisibility
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Feralan                                          \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Feralan OR druid_all BEGIN 

// shapeshifters get locked out of all armor, either by the druid flag or their individual kit flag
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  READ_BYTE 0x1C "type" ELSE 0 // skips invalid files
  PATCH_IF (("%type%" = 2) OR (("%type%" > 59) AND ("%type%" < 69))) BEGIN // add scale mail to check
    READ_BYTE 0x21 "druid"
    READ_BYTE 0x29 "shapeshifter"
    PATCH_IF (("%druid%" BAND 0b01000000) = 0b01000000) BEGIN // if unusable by druids
      WRITE_BYTE 0x29 ("%shapeshifter%" BOR 0b00010000) // remove redundant shapeshifter restriction; shapeshifters can't use it 'coz of druid flag //it is a ranger kit and not a druid kit, so we need to keep them
    END ELSE BEGIN
      WRITE_BYTE 0x29 ("%shapeshifter%" BOR 0b00010000) // making unusable by shapeshifters
    END
  END
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~spcl321.spl~ ~override/a#fera02.spl~ // 'Feral Rage' innate
  SAY NAME1 @40604

COPY ~divine_remix/spl/A#fera03.spl~ ~override~ // 'Call of the Wild' innate
  SAY NAME1 @40605
  SAY NAME2 @40605
  SAY UNIDENTIFIED_DESC  @40610
  SAY DESC  @40610

COPY ~divine_remix/cre/a#fera01.cre~ ~override~ // Wild Dog
  SAY NAME1 @40606
  SAY NAME2 @40606

COPY ~divine_remix/cre/a#fera02.cre~ ~override~ // Wolf
  SAY NAME1 @40607
  SAY NAME2 @40607

COPY ~divine_remix/cre/a#fera03.cre~ ~override~ // Dire Wolf
  SAY NAME1 @40608
  SAY NAME2 @40608

COPY ~divine_remix/cre/a#fera04.cre~ ~override~ // Pack Leader
  SAY NAME1 @40609
  SAY NAME2 @40609

COPY ~divine_remix/spl/a#fera01.spl~ ~override~ // +10% Stealth
     ~divine_remix/eff/a#fera01.eff~ ~override~
     ~divine_remix/eff/a#fera02.eff~ ~override~
     ~divine_remix/eff/a#fera03.eff~ ~override~
     ~divine_remix/eff/a#fera04.eff~ ~override~

ADD_KIT ~A#FERALAN~
  ~A#FERALAN		1	1	1	1	1	1	1	1~
  ~A#FERALAN 1 1 2 2 2 1 2 2 1 1 1 2 1 1 1 2 2 2 2 1 1 2 2 1 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#FERALAN	13	13	14	0	14	0~
  ~A#FERALAN		0	0	0	0	0	-2~
  ~A#FERALAN		17	17	0	0	17	0~
  ~A#FERALAN		15	15	0	0	15	0~
  ~A#FERALAN		0	0	0	1	0	0	1	0	0~
  ~A#FERALAN		0	1	0	0	0	0~
  ~divine_remix/2da/a#feral.2da~
  ~K_R_H K_R_HE K_R_E~
  ~0x10000000	12~
  ~ra0~
  ~* * HELM19 BAG27 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @40601
  SAY @40602
  SAY @40603

LAF fl#add_kit_ee
  STR_VAR
    kit_name = ~A#FERALAN~
    clascolr = ~35 67 67 25 80~
END
END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Forest Runner                                    \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Forest OR druid_all BEGIN 

ADD_KIT NMRNFRRN // ROWNAME in KITLIST.2da
  ~NMRNFRRN                1           1           1           1           1           1           1           1~ // CLASWEAP.2DA (weapons class can use)
  ~NMRNFRRN 2 2 2 2 2 2 2 2 2 3 2 1 1 2 2 3 1 2 2 2 2 2 3 1 3 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~ // WEAPPROF (proficiency points this kit can place)
  ~NMRNFRRN                13      13      14      0       14      15~ // ABCLASRQ.2da (minimum stats)
  ~NMRNFRRN                0       0       0       0       0       0~ // ABCLSMOD.2da (stat modifiers)
  ~NMRNFRRN                17      17      0       0       17      0~ // ABDCDSRQ.2da (minimum stats needed to dual-class from this class)
  ~NMRNFRRN                15      15      0       0       15      0~ // ABDCSCRQ.2da (minimum stats needed to dual-class to this class)
  ~NMRNFRRN                1       0       0       1       0       0       1       0       0~ // ALIGNMNT.2da (alignments this kit can be)
  ~NMRNFRRN                0       1       0       0       0       0~ // DUALCLAS.2da (classes this kit can be dualed with)
  ~divine_remix/2da/nmrnfrrn.2da~ // CLAB****.2da (abilities file)
  ~K_R_E K_R_H K_R_HE~ // K_B_H.2da, K_B_HE.2da, etc (class/race restrictions)
  ~0x00008000 12~ // UNUSABLE in KITLIST.2da (item restriction flag this kit uses)
  ~Ra0~ // LuBa0.2da, LuBa1.2da, etc (high level abilities file)
  ~LEAT20 DART03,40 HELM07 BAG26 RING06 RING31 CLCK27 BOOT01 AMUL19 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW11 BOW19 XBOW06~ // ToB starting equipment (PC only)
  SAY @40901 // Kit name without capitals
  SAY @40902 // Kit name with capitals
  SAY @40903 // Full kit description

LAF fl#add_kit_ee
  STR_VAR
    kit_name = ~nmrnfrrn~
    clascolr = ~35 67 67 25 80~
END

COPY ~divine_remix/spl/nmrnfr1.spl~ ~override~ // +5% Stealth

COPY ~divine_remix/spl/nmrnfr2.spl~ ~override~ // 'Inspire' innate
  SAY NAME1 @40904
  SAY NAME2 @40904
  SAY 0xfe  @40905
  SAY UNIDENTIFIED_DESC  @40906
  SAY DESC  @40906

END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Justifier                                        \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Justifier OR druid_all BEGIN 

ADD_KIT ~A#JUSTIFIER~
  ~A#JUSTIFIER		1	1	1	1	1	1	1	1~
  ~A#JUSTIFIER 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~A#JUSTIFIER	13	13	14	0	14	0~
  ~A#JUSTIFIER		0	0	0	0	0	0~
  ~A#JUSTIFIER		17	17	0	0	17	0~
  ~A#JUSTIFIER		15	15	0	0	15	0~
  ~A#JUSTIFIER		1	0	0	0	0	0	0	0	0~
  ~A#JUSTIFIER		0	0	0	0	0	0~
  ~divine_remix/2da/a#justif.2da~
  ~K_R_H K_R_HE K_R_E~
  ~0x00004000	12~
  ~ra0~
  ~LEAT20 * HELM19 BAG27 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @41201
  SAY @41202
  SAY @41203

LAF fl#add_kit_ee
  STR_VAR
    kit_name = ~A#JUSTIFIER~
    clascolr = ~35 67 67 25 80~
END

COPY ~divine_remix/spl/a#just01.spl~ ~override~ // +10% Stealth
     ~divine_remix/spl/a#just02.spl~ ~override~ // +1 to speed factor and to hit
     ~divine_remix/spl/a#justns.spl~ ~override~ // Removes priest spells

// change spells to innates as needed
COPY_EXISTING ~sppr103.spl~ ~override/a#justcl.spl~ // 'cure light wounds'
              ~sppr111.spl~ ~override/a#justaf.spl~ // 'armour of faith'
              ~spwi209.spl~ ~override/a#justlu.spl~ // 'luck'
              ~sppr108.spl~ ~override/a#justrf.spl~ // 'remove fear'
  LAUNCH_PATCH_MACRO ~spell_to_innate~ // change to innate spell
  BUT_ONLY_IF_IT_CHANGES

END

/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Wilderness Runner                                \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_IF Wilderness OR druid_all BEGIN 

ADD_KIT NMRNWLRN // ROWNAME in KITLIST.2da
  ~NMRNWLRN                1           1           1           1           1           1           1           1~ // CLASWEAP.2DA (weapons class can use)
  ~NMRNWLRN 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 1 2 3 2 3 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~ // WEAPPROF (proficiency points this kit can place)
  ~NMRNWLRN                13      13      14      0       14      15~ // ABCLASRQ.2da (minimum stats)
  ~NMRNWLRN                0       0       0       0       0       -2~ // ABCLSMOD.2da (stat modifiers)
  ~NMRNWLRN                17      17      0       0       17      0~ // ABDCDSRQ.2da (minimum stats needed to dual-class from this class)
  ~NMRNWLRN                15      15      0       0       15      0~ // ABDCSCRQ.2da (minimum stats needed to dual-class to this class)
  ~NMRNWLRN                1       0       0       1       0       0       1       0       0~ // ALIGNMNT.2da (alignments this kit can be)
  ~NMRNWLRN                0       1       0       0       0       0~ // DUALCLAS.2da (classes this kit can be dualed with)
  ~divine_remix/2da/nmrnwlrn.2da~ // CLAB****.2da (abilities file)
  ~K_R_E~ // K_B_H.2da, K_B_HE.2da, etc (class/race restrictions)
  ~0x00010000 12~ // UNUSABLE in KITLIST.2da (item restriction flag this kit uses)
  ~Ra0~ // LuBa0.2da, LuBa1.2da, etc (high level abilities file)
  ~LEAT20 DART03,40 HELM07 BAG26 RING06 RING31 CLCK27 BOOT01 AMUL19 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW11 BOW19 XBOW06~ // ToB starting equipment (PC only)
  SAY @41501 // Kit name without capitals
  SAY @41502 // Kit name with capitals
  SAY @41503 // Full kit description

LAF fl#add_kit_ee
  STR_VAR
    kit_name = ~nmrnwlrn~
    clascolr = ~35 67 67 25 80~
END

COPY ~divine_remix/spl/nmrnwr1.spl~ ~override~ // 'Enhanced Charm Animal' innate
  SAY NAME1 @41504
  SAY NAME2 @41504
  SAY UNIDENTIFIED_DESC @41505
  SAY DESC @41505

COPY_EXISTING ~spcl412.spl~ ~override/nmrnwr2.spl~ // Set Snare

COPY ~divine_remix/spl/nmrnwr3.spl~ ~override~ // +10% Fire and Cold Resistance
     ~divine_remix/spl/nmrnwr4.spl~ ~override~ // +20% set snares

COPY_EXISTING ~nmrnwr4.spl~ ~override/nmrnwr5.spl~ // +5% set snares
  WRITE_LONG 0x9e 5

END